name: Deploy

# Trigger the workflow on push and 
# pull request events on the production branch
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      
# Authenticate to the the server via ssh 
# and run our deployment script 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ sg.magic-jungle.com }}
          username: ${{ rdodevs3 }}
          port: ${{ 2083 }}
          key: ${{ -----BEGIN RSA PRIVATE KEY-----
MIIJKAIBAAKCAgEAtDSpPSQHGM0KhMUYlqFaJvVc3KvXWqWDCRHARfvpoZlvXBrN
L9MYPur982OYT0CvDrZI0A7vYxkINrrQ42ySX/3p9TTg3Lz/3lXbIbu0EtPdC5oK
zfPkWQpHIawN+SB0zBRt0cdb0SJudQ1VpEhdrlcnTsJi76gw4QVXPfZkueCVZGJz
e9iYDCqhmgi4YMrTIFd9aLJBLEUfUlGjbpA7fIVMkX/QLCquqk0oPxFyLTz9HBIf
kbeguU2Q+ZnaRjd9mwjSy7vFXn105r57YiCFgAYUgHCwHcLJmLHVCqiqsCAf5o3n
mPiZhUmENMNp4UCYOlLO0mS4SrGRTQK+eM+HvszK+3uKScc7/DmUq60yR+j6iKnd
uUB64phIji16JBMH8T+BezYWwz3I5Vn59QY0elBqOZTPPJLGNCXl1A6TlHsobpv3
f5+b3+NVxU8YDWtRxf59jlwvbfp6LLlKVwp1rAxrPUs0TgwnYZS0WT/fx25cxEUV
jpA6jer9gBQtnZYpsH0Eli5HSZk4isTNc1GJC1wcmYV2ceRVgl8+8iPk+SkHr0r9
O2wtn8nL8QPLKTif26KKvx6seg/sjEX0e7D0stXLu9ZRAkeaUugSzSZ54rX0ZtwB
xws3UyPhABl58eueUbBHSyQLnOpBNe0wptl/psObwhJHnJVBlaWHSzjNIpMCAwEA
AQKCAgBHEXWlDS5XU5XQYsKdtSiOsLlctdCKiTeyPfPsJbsv5gkK8+7z63ZmadqZ
QC/zIXlofe8dTqaOGHMq0mZLKqhXfxXjhGUh6M+n6YgwN4x+2FsWljuomYT2sJz4
5JfmJiypx2zADLVjNwcE1qttzLRVaz2vS+4kwdn1BFwxrZhvzehc3I7aysK8GZv9
2W6Nja/R0287+QDG6sO9fUDM+8jaBN/7icKZiIO12hQDO2gh+yl/Bo64swiJy9Ne
/JQemQfKOqKXgogGCcgur/SM8HJ12PAA73AlbIqA07FHMNmP+Dtce55Yr8Ir1KB1
BpQdJ5JhfgLe6qXbn0fEbU6c6ouHxGWg//IWv+8a/NYbTKGNpiBBed7mMISqDbS4
GM2/aCgd4paowBBFD8rsu1RsmaU4uieAcqZF9b+b6H2eVXYMPCoLtF/32L4V2THv
oa4BTjgMd5YGPzDkPqtuzaR9hnHPnZaQd+Ue2HeUv9PQOZEJfLj2cqeWTi244aP4
YxISPqqKsS8DBq7OW2ram0qdAD7PDLS+GmiO+rkmORhlh4IJNKqdXH11FSPLHfU9
ceIPMPoU95htQ52Hq0IhyoVRc5QVFUO5W3n3l4SGC0togBSSVXNhntEAAZR5fcSh
NFlsBdZAEwu+EbzkNVK9QyQ86zGTHHfrYVT15XscOWO+K3xwcQKCAQEA2CW1XPXf
t7qoJvRGl49DIdd5/s1Fl5cF+MgwKjANqRnfFuK0QsMl3byFUoDuugp/HPWNfZOz
01Sgk/ndbpC1pt5wWQ//33ILIw196A5JV3mz6gLBwQSzMlg1vZXxHa6OqzXG91QA
ojimViVbwkK4/pUnYy+rGJQRwaIUqpSpDtzbikiJf17qyRLykWbZKpGqL0NnXqqD
88GizATolC8JxS4GL3HDJdP9XWCq+KxbEDMIfEYJAvyUOQQLa+22BH6JtotvMFME
7X82frJB2PfQLgDvcQvjORBb2H/FAOd51w3gvGAZfF5cITVkstGejhhwZjupZI2q
qF68rKaTcEEGbQKCAQEA1W58hVx3CSC/TYykr5vTMpDJbqk0DoZf27cQSNe0YHc2
cWU8l8GgWJSKmPuhWM3nAFg4OQA300HwCllnSqXOyAYqkkPUXtHKiVUgj0FcoRzs
EaRcjP3i3GvCy0Hd9ksBuz3rnbDj/bA9YThIarjwHEcThrGuPb8ZD2r4SdF6l8Yh
83NdqwbTyWtdJZTVwDxDwz7KooBSdgOcMzkZoMBT/wpuf+6U6ePN3lc7byTlYmUy
2mI4HlBc7V/TgsYYDZfFYxJGg+0e/mz9Exd8/Ecnh3BV+iiD5Zm7ga1FOpQ/jQsz
08D9bA9e6eamC073V9a3wspgaq/ov8UEY9SUNoEs/wKCAQBsTLCLrHJ0t2SrZ/e6
1sBXQ4TPw4BcDQKj/YIMkVk24kyiReL2FJtzd5MBnLKAquO32d0UD56pg5yVqDtn
u8AYpRl7toWJKrYj0Q3F6OqcltErrkfwc29qCUKcBHX0XlMDvAU+RWuv3FyTi1Jn
ilDw1kEO9IJw5TfkYlaihawTU1v49JFYLXHMX98ENZkYODYiSk6P4zYMO3hbaxYx
sUPe9UmKGiEiYg5v7BCeWpWiDz/wLJM1WOLXkow6freVluVffouuldpBOV1Pq/dM
RBaeBj/yz3cBT44Fczd9VX353+071ZbPduQIi50x78/W+K3Qu5ILXOQmSpmUlD4J
n7sdAoIBAGi1Q7HJozx/LFtHXKQqtnpgPfJkYH2fvvdz4DFcYcnRsov/NrLc82WB
ul1DVezTVzj8DtkoGjsyZikto1cj8UaAf/IyBMZf9hVaBhdB4cfJAKfHEwC4rcul
snM1ZUenlLnfrvA2ECQtim9fxWdWQ7YbyKCUGv9/+TNvL1BHzPUY5x8gwhtdxhlS
6ue9FQCykCwBajg+7DWpn8Ahi0kqEgtVetCYo8X7VMx3z1i/qSmUrFYnSZDVrEFo
ecP2m2ZPxy7LkHy4oDQCFEaBh3fdEK+JlSSdK9hAi5UbBJOwl10C2fJRBAM3p0Dp
PxzdKMuXM6AE2Th+BJnQdk7jw7LZvNECggEBAMC1IlT0g7Tf+WR4WKR6LXl53FPr
PFJcogPOmmSZN/Mhg3s6ufUzQ1aftCWZP7/T1N863rdirMDrE4hnQ35ph/Ai8jmN
DHnyWqUDWQxRlL5CuLXuk29yPakWf3NRkeF8yUi52XEtRozAfpwMe+Jt4NiiJGVl
Jj6wOZf3OTMhGesB0LbCv6AlZP2vkLK88mwf7qrLtxFzOEAecrXYLY29Sy3zWEjc
4DHOr/fr3coN2IzcAhmuJYX5EBHpnqBQ/gt2jn8sAI6xOh7XE8sc3OBCXvJLDS9g
D9W6Z78pCV3OuorcnXi4tLZsXEFXQvY5BSDmdPCXazqeNJNrhzHOp8gkZqs=
-----END RSA PRIVATE KEY----- }}
          script: "cd /www/test && ./.scripts/deploy.sh"