name: publish

on:
  push:
    branches: [ "dev" ]

# env:
  # Use docker.io for Docker Hub if empty
  # REGISTRY: ghcr.io
  # IMAGE_NAME: test-auto-deploy:latest

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Deploy to server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            # password: ${{ secrets.PASSWORD }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.SSHPORT }}
            # script: "ls"
            script: "./test_docker_deploy"
            debug: true